version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/usr/src/app
      # - ./web:.
    links:
      - db
  db:
    build: ./db
    volumes:
      - ./db/data:/data/db
